//LOCALHOST
### Base Route
GET http://localhost:8080

### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/645cf8a44428d190e0028874

### Create new contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Random",
    "lastName":"Joe",
    "email":"rando@email.com",
    "favoriteColor":"green",
    "birthday":"5/5/05"
}

### Update contact by ID
PUT http://localhost:8080/contacts/645cf8a44428d190e0028874 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Random",
    "lastName":"Joe",
    "email":"rando@email.com",
    "favoriteColor":"purple",
    "birthday":"5/5/05"
}

### Delete contact by ID
DELETE http://localhost:8080/contacts/<id>

--------------------------------------------------------------------------------

// PRODUCTION DISPLAY (render.com)
### Base Route
GET https://contacts-fh43.onrender.com/

### Get all contacts
GET https://contacts-fh43.onrender.com/contacts

### Get single contact by ID
GET https://contacts-fh43.onrender.com/contacts/6457158e0a338e56a0403db7

### Create new contact
POST https://contacts-fh43.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"New",
    "lastName":"Guy",
    "email":"newbie@email.com",
    "favoriteColor":"gray",
    "birthday":"5/5/05"
}

### Update contact by ID
PUT https://contacts-fh43.onrender.com/contacts/645cf9b87c691d903facc416 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Big",
    "lastName": "Blue",
    "email": "blueboy@email.com",
    "favoriteColor": "green",
    "birthday": "1/1/11"
}

### Delete contact by ID
DELETE https://contacts-fh43.onrender.com/contacts/6457158e0a338e56a0403db7